backend:
  name: github
  repo: mikeyp/beefheart
  base_url: https://ges7shklsl.execute-api.us-east-1.amazonaws.com
  branch: master
  auth_endpoint: /prod/auth
publish_mode: editorial_workflow
media_folder: "static/uploads"
public_folder: "/uploads"
collections:
  - name: "pages"
    label: "Pages"
    folder: "src/pages"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - label: "Redirects"
        name: "redirect_from"
        widget: "list"
        required: false
        field: {label: "URL", name: "url", widget: "string", hint: "Must begin and end with a forward slash. i.e. \"/old-path/\""}
      - {label: "Body", name: "body", widget: "markdown"}
  - name: "posts"
    label: "Blog posts"
    folder: "src/blog"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - label: "Title"
        name: "title"
        widget: "string"
      - label: "Subtitle"
        name: "subtitle"
        widget: "string"
        required: false
      - label: "Path"
        name: "path"
        widget: "string"
        default: "/blog/"
      - label: "Publish Date"
        name: "date"
        widget: "datetime"
      - label: "Redirects"
        name: "redirect_from"
        widget: "list"
        required: false
        field: {label: "URL", name: "url", widget: "string", hint: "Must begin and end with a forward slash. i.e. \"/old-path/\""}
      - label: "Background Image"
        name: "background_image"
        widget: "image"
        allow_multiple: false
        required: false
        media_library:
          config:
            multiple: false
      - label: "Body"
        name: "body"
        widget: "markdown"
